# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

steps:
- task: Snyk.snyk-security-scan.custom-build-release-task.SnykSecurityScan@1
- task: SnykSecurityScan@1
  inputs:
    serviceConnectionEndpoint: 'snyk-service'
    testType: 'app'
    monitorWhen: 'always'
    failOnIssues: false
  displayName: 'Snyk scan for open source vulnerabilities'
  inputs:
    serviceConnectionEndpoint: 'snyk-service'
    testType: container
    dockerImageName: goof
    dockerfilePath: '**/Dockerfile'
    failOnIssues: false
    projectName: 'snyk-docker-test5'
    organization: '73950804-3a17-4604-8144-192f83dad018'

